<a href="https://colab.research.google.com/github/Yurii1960/goit-algo-hw-04/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_Hw2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
import numpy as np

import requests
from io import StringIO

url = "https://uk.wikipedia.org/wiki/%D0%9D%D0%B0%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B8#%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%B6%D1%83%D0%B2%D0%B0%D0%BD%D1%96%D1%81%D1%82%D1%8C"

headers = {
"User-Agent": "Mozilla/5.0",
"Accept-Language": "uk-UA,uk;q=0.9,en;q=0.8",
}

html = requests.get(url, headers=headers, timeout=30).text

df = pd.read_html(
StringIO(html),
match="Коефіцієнт народжуваності в регіонах України",
thousands=".", decimal=","
)[0]

df

               Регіон  1950  1960  1970  1990  2000  2012  2014  2019
0                Крим  23.0  20.6  16.0  13.0   7.3  12.6     —     —
1           Вінницька  22.4  19.2  14.2  12.4   8.4  11.2  10.9   7.6
2           Волинська  24.7  25.0  17.9  15.3  11.2  14.8  14.1  10.1
3    Дніпропетровська  20.4  20.4  15.1  12.3   7.1  11.2  11.1   7.1
4            Донецька  27.1  21.4  14.0  10.9   6.1   9.8   8.2     —
5         Житомирська  26.1  22.3  15.9  12.9   8.9  12.2  12.0   7.9
6        Закарпатська  31.4  27.3  20.7  16.8  11.5  15.1  14.6  10.4
7          Запорізька  21.9  19.7  15.0  12.4   7.1  10.6  10.6   6.8
8   Івано-Франківська  24.3  24.8  18.2  15.5  10.3  12.4  12.2   8.8
9            Київська  20.4  18.9  15.6  12.3   7.3  12.2  12.1   8.0
10     Кіровоградська  21.6  17.1  14.5  12.6   7.9  11.0  10.8   6.8
11          Луганська  26.2  23.5  14.4  11.6   6.2   9.6   5.1     —
12          Львівська  23.4  24.0  17.1  14.0   9.1  11.9  11.9   8.7
13       Миколаївська  21.1  19.4  15.5  13.7   8.0  11.5  11.2   7.1
14            Одеська  24.1  19.2  14.8  12.6   8.0  12.7  12.3   8.8
15         Полтавська  18.6  16.3  13.1  11.8   7.0   9.9  10.0   6.5
16         Рівненська  26.9  26.7  19.3  15.8  11.8  15.9  14.8  10.7
17            Сумська  21.6  18.4  13.2  11.5   7.0   9.7   9.2   6.0
18      Тернопільська  21.3  21.6  15.7  14.2   9.2  11.3  10.9   7.6
19         Харківська  19.7  17.3  14.0  11.4   6.8   9.9  10.1   6.8
20         Херсонська  20.8  21.4  16.6  14.3   8.5  11.7  11.5   8.1
21        Хмельницька  23.4  19.8  14.8  12.9   8.5  11.3  11.2   7.9
22          Черкаська  20.5  17.9  14.4  12.3   7.5  10.0   9.8   6.4
23        Чернівецька  24.7  21.8  17.0  14.8  10.1  12.8  12.9   9.2
24       Чернігівська  22.0  18.3  12.7  10.8   6.9   9.4   9.0   6.1
25               Київ   NaN  17.4  15.9  12.0   7.3  12.0  12.1  11.0
26        Севастополь   NaN   NaN   NaN  12.5   7.0  12.0     —     —
27            Україна  22.8  20.5  15.2  12.6   7.8  11.4  11.1   8.1

In [ ]:
df.isnull().sum()

Регіон    0
1950      2
1960      1
1970      1
1990      0
2000      0
2012      0
2014      0
2019      0
dtype: int64

In [ ]:
data=df.dropna(axis=1)
data

               Регіон  1990  2000  2012  2014  2019
0                Крим  13.0   7.3  12.6     —     —
1           Вінницька  12.4   8.4  11.2  10.9   7.6
2           Волинська  15.3  11.2  14.8  14.1  10.1
3    Дніпропетровська  12.3   7.1  11.2  11.1   7.1
4            Донецька  10.9   6.1   9.8   8.2     —
5         Житомирська  12.9   8.9  12.2  12.0   7.9
6        Закарпатська  16.8  11.5  15.1  14.6  10.4
7          Запорізька  12.4   7.1  10.6  10.6   6.8
8   Івано-Франківська  15.5  10.3  12.4  12.2   8.8
9            Київська  12.3   7.3  12.2  12.1   8.0
10     Кіровоградська  12.6   7.9  11.0  10.8   6.8
11          Луганська  11.6   6.2   9.6   5.1     —
12          Львівська  14.0   9.1  11.9  11.9   8.7
13       Миколаївська  13.7   8.0  11.5  11.2   7.1
14            Одеська  12.6   8.0  12.7  12.3   8.8
15         Полтавська  11.8   7.0   9.9  10.0   6.5
16         Рівненська  15.8  11.8  15.9  14.8  10.7
17            Сумська  11.5   7.0   9.7   9.2   6.0
18      Тернопільська  14.2   9.2  11.3  10.9   7.6
19         Харківська  11.4   6.8   9.9  10.1   6.8
20         Херсонська  14.3   8.5  11.7  11.5   8.1
21        Хмельницька  12.9   8.5  11.3  11.2   7.9
22          Черкаська  12.3   7.5  10.0   9.8   6.4
23        Чернівецька  14.8  10.1  12.8  12.9   9.2
24       Чернігівська  10.8   6.9   9.4   9.0   6.1
25               Київ  12.0   7.3  12.0  12.1  11.0
26        Севастополь  12.5   7.0  12.0     —     —
27            Україна  12.6   7.8  11.4  11.1   8.1

In [ ]:

df['2019'][5]

'7.9'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Регіон  28 non-null     object
 1   1950    26 non-null     float64
 2   1960    27 non-null     float64
 3   1970    27 non-null     float64
 4   1990    28 non-null     float64
 5   2000    28 non-null     float64
 6   2012    28 non-null     float64
 7   2014    28 non-null     object
 8   2019    28 non-null     object
dtypes: float64(6), object(3)
memory usage: 2.1+ KB

In [ ]:
df_sorted=df.sort_values(by='2012',ascending=False)
m=df_sorted['2012'].mean()
print(m)
df_gm=df.loc[df['2012']>m]
df_gm
df_gm['Регіон']

11.646428571428572

0                  Крим
2             Волинська
5           Житомирська
6          Закарпатська
8     Івано-Франківська
9              Київська
12            Львівська
14              Одеська
16           Рівненська
20           Херсонська
23          Чернівецька
25                 Київ
26          Севастополь
Name: Регіон, dtype: object

In [ ]:
print(df.loc[df['2012']>12])

               Регіон  1950  1960  1970  1990  2000  2012  2014  2019
0                Крим  23.0  20.6  16.0  13.0   7.3  12.6     —     —
2           Волинська  24.7  25.0  17.9  15.3  11.2  14.8  14.1  10.1
5         Житомирська  26.1  22.3  15.9  12.9   8.9  12.2  12.0   7.9
6        Закарпатська  31.4  27.3  20.7  16.8  11.5  15.1  14.6  10.4
8   Івано-Франківська  24.3  24.8  18.2  15.5  10.3  12.4  12.2   8.8
9            Київська  20.4  18.9  15.6  12.3   7.3  12.2  12.1   8.0
14            Одеська  24.1  19.2  14.8  12.6   8.0  12.7  12.3   8.8
16         Рівненська  26.9  26.7  19.3  15.8  11.8  15.9  14.8  10.7
23        Чернівецька  24.7  21.8  17.0  14.8  10.1  12.8  12.9   9.2

In [ ]:
df.shape[0]

28

In [ ]:
columns_name=df.columns
columns_name[1:]

Index(['1950', '1960', '1970', '1990', '2000', '2012', '2014', '2019'], dtype='object')

In [ ]:
df['2014']=pd.to_numeric(df['2014'])
df['2019']=pd.to_numeric(df['2019'])
df.dtypes

Регіон     object
1950      float64
1960      float64
1970      float64
1990      float64
2000      float64
2012      float64
2014      float64
2019      float64
dtype: object

In [ ]:
df_new.drop([1])

               Регіон  1950  1960  1970  1990  2000  2012  2014  2019
0                Крим  23.0  20.6  16.0  13.0   7.3  12.6   NaN   NaN
2           Волинська  24.7  25.0  17.9  15.3  11.2  14.8  14.1  10.1
3    Дніпропетровська  20.4  20.4  15.1  12.3   7.1  11.2  11.1   7.1
4            Донецька  27.1  21.4  14.0  10.9   6.1   9.8   8.2   NaN
5         Житомирська  26.1  22.3  15.9  12.9   8.9  12.2  12.0   7.9
6        Закарпатська  31.4  27.3  20.7  16.8  11.5  15.1  14.6  10.4
7          Запорізька  21.9  19.7  15.0  12.4   7.1  10.6  10.6   6.8
8   Івано-Франківська  24.3  24.8  18.2  15.5  10.3  12.4  12.2   8.8
9            Київська  20.4  18.9  15.6  12.3   7.3  12.2  12.1   8.0
10     Кіровоградська  21.6  17.1  14.5  12.6   7.9  11.0  10.8   6.8
11          Луганська  26.2  23.5  14.4  11.6   6.2   9.6   5.1   NaN
12          Львівська  23.4  24.0  17.1  14.0   9.1  11.9  11.9   8.7
13       Миколаївська  21.1  19.4  15.5  13.7   8.0  11.5  11.2   7.1
14            Одеська  24.1  19.2  14.8  12.6   8.0  12.7  12.3   8.8
15         Полтавська  18.6  16.3  13.1  11.8   7.0   9.9  10.0   6.5
16         Рівненська  26.9  26.7  19.3  15.8  11.8  15.9  14.8  10.7
17            Сумська  21.6  18.4  13.2  11.5   7.0   9.7   9.2   6.0
18      Тернопільська  21.3  21.6  15.7  14.2   9.2  11.3  10.9   7.6
19         Харківська  19.7  17.3  14.0  11.4   6.8   9.9  10.1   6.8
20         Херсонська  20.8  21.4  16.6  14.3   8.5  11.7  11.5   8.1
21        Хмельницька  23.4  19.8  14.8  12.9   8.5  11.3  11.2   7.9
22          Черкаська  20.5  17.9  14.4  12.3   7.5  10.0   9.8   6.4
23        Чернівецька  24.7  21.8  17.0  14.8  10.1  12.8  12.9   9.2
24       Чернігівська  22.0  18.3  12.7  10.8   6.9   9.4   9.0   6.1
25               Київ   NaN  17.4  15.9  12.0   7.3  12.0  12.1  11.0
26        Севастополь   NaN   NaN   NaN  12.5   7.0  12.0   NaN   NaN
27            Україна  22.8  20.5  15.2  12.6   7.8  11.4  11.1   8.1

In [ ]:
#new_df=df.drop(['Регіон'],axis=1)
columns_name=df.columns
print(columns_name)
for col in columns_name[1:]:
  df=df.fillna({col:new_df[col].mean()})
df

Index(['Регіон', '1950', '1960', '1970', '1990', '2000', '2012', '2014',
       '2019'],
      dtype='object')

,Регіон,1950,1960,1970,1990,2000,2012,2014,2019
0,Крим,23.000000,20.600000,16.000000,13.0,7.3,12.6,11.142308,8.020833
1,Вінницька,22.400000,19.200000,14.200000,12.4,8.4,11.2,10.900000,7.600000
2,Волинська,24.700000,25.000000,17.900000,15.3,11.2,14.8,14.100000,10.100000
3,Дніпропетровська,20.400000,20.400000,15.100000,12.3,7.1,11.2,11.100000,7.100000
4,Донецька,27.100000,21.400000,14.000000,10.9,6.1,9.8,8.200000,8.020833
5,Житомирська,26.100000,22.300000,15.900000,12.9,8.9,12.2,12.000000,7.900000
6,Закарпатська,31.400000,27.300000,20.700000,16.8,11.5,15.1,14.600000,10.400000
7,Запорізька,21.900000,19.700000,15.000000,12.4,7.1,10.6,10.600000,6.800000
8,Івано-Франківська,24.300000,24.800000,18.200000,15.5,10.3,12.4,12.200000,8.800000
9,Київська,20.400000,18.900000,15.600000,12.3,7.3,12.2,12.100000,8.000000
10,Кіровоградська,21.600000,17.100000,14.500000,12.6,7.9,11.0,10.800000,6.800000
11,Луганська,26.200000,23.500000,14.400000,11.6,6.2,9.6,5.100000,8.020833
12,Львівська,23.400000,24.000000,17.100000,14.0,9.1,11.9,11.900000,8.700000
13,Миколаївська,21.100000,19.400000,15.500000,13.7,8.0,11.5,11.200000,7.100000
14,Одеська,24.100000,19.200000,14.800000,12.6,8.0,12.7,12.300000,8.800000
15,Полтавська,18.600000,16.300000,13.100000,11.8,7.0,9.9,10.000000,6.500000
16,Рівненська,26.900000,26.700000,19.300000,15.8,11.8,15.9,14.800000,10.700000
17,Сумська,21.600000,18.400000,13.200000,11.5,7.0,9.7,9.200000,6.000000
18,Тернопільська,21.300000,21.600000,15.700000,14.2,9.2,11.3,10.900000,7.600000
19,Харківська,19.700000,17.300000,14.000000,11.4,6.8,9.9,10.100000,6.800000
20,Херсонська,20.800000,21.400000,16.600000,14.3,8.5,11.7,11.500000,8.100000
21,Хмельницька,23.400000,19.800000,14.800000,12.9,8.5,11.3,11.200000,7.900000
22,Черкаська,20.500000,17.900000,14.400000,12.3,7.5,10.0,9.800000,6.400000
23,Чернівецька,24.700000,21.800000,17.000000,14.8,10.1,12.8,12.900000,9.200000
24,Чернігівська,22.000000,18.300000,12.700000,10.8,6.9,9.4,9.000000,6.100000
25,Київ,23.092308,17.400000,15.900000,12.0,7.3,12.0,12.100000,11.000000
26,Севастополь,23.092308,20.748148,15.585185,12.5,7.0,12.0,11.142308,8.020833
27,Україна,22.800000,20.500000,15.200000,12.6,7.8,11.4,11.100000,8.100000

In [ ]:

columns_name=new_df.columns
print(columns_name)
for col in columns_name:
  new_df=new_df.fillna({col:new_df[col].mean()})
#col.dtypes

#df=df.fillna({col:df[col].mean()})
new_df

Index(['Регіон', '1950', '1960', '1970', '1990', '2000', '2012', '2014',
       '2019'],
      dtype='object')

TypeError: Could not convert string 'КримВінницькаВолинськаДніпропетровськаДонецькаЖитомирськаЗакарпатськаЗапорізькаІвано-ФранківськаКиївськаКіровоградськаЛуганськаЛьвівськаМиколаївськаОдеськаПолтавськаРівненськаСумськаТернопільськаХарківськаХерсонськаХмельницькаЧеркаськаЧернівецькаЧернігівськаКиївСевастопольУкраїна' to numeric

In [ ]:
df.dtypes

Регіон     object
1950      float64
1960      float64
1970      float64
1990      float64
2000      float64
2012      float64
2014       object
2019       object
dtype: object

In [ ]:
# частка пропусків в колонці в %
df.isnull().sum()/(df.shape[0]-1)*100

NameError: name 'df' is not defined

In [ ]:
#видаляємо останній рядок
new_data=df[:-1]
new_data

               Регіон  1950  1960  1970  1990  2000  2012  2014  2019
0                Крим  23.0  20.6  16.0  13.0   7.3  12.6     —     —
1           Вінницька  22.4  19.2  14.2  12.4   8.4  11.2  10.9   7.6
2           Волинська  24.7  25.0  17.9  15.3  11.2  14.8  14.1  10.1
3    Дніпропетровська  20.4  20.4  15.1  12.3   7.1  11.2  11.1   7.1
4            Донецька  27.1  21.4  14.0  10.9   6.1   9.8   8.2     —
5         Житомирська  26.1  22.3  15.9  12.9   8.9  12.2  12.0   7.9
6        Закарпатська  31.4  27.3  20.7  16.8  11.5  15.1  14.6  10.4
7          Запорізька  21.9  19.7  15.0  12.4   7.1  10.6  10.6   6.8
8   Івано-Франківська  24.3  24.8  18.2  15.5  10.3  12.4  12.2   8.8
9            Київська  20.4  18.9  15.6  12.3   7.3  12.2  12.1   8.0
10     Кіровоградська  21.6  17.1  14.5  12.6   7.9  11.0  10.8   6.8
11          Луганська  26.2  23.5  14.4  11.6   6.2   9.6   5.1     —
12          Львівська  23.4  24.0  17.1  14.0   9.1  11.9  11.9   8.7
13       Миколаївська  21.1  19.4  15.5  13.7   8.0  11.5  11.2   7.1
14            Одеська  24.1  19.2  14.8  12.6   8.0  12.7  12.3   8.8
15         Полтавська  18.6  16.3  13.1  11.8   7.0   9.9  10.0   6.5
16         Рівненська  26.9  26.7  19.3  15.8  11.8  15.9  14.8  10.7
17            Сумська  21.6  18.4  13.2  11.5   7.0   9.7   9.2   6.0
18      Тернопільська  21.3  21.6  15.7  14.2   9.2  11.3  10.9   7.6
19         Харківська  19.7  17.3  14.0  11.4   6.8   9.9  10.1   6.8
20         Херсонська  20.8  21.4  16.6  14.3   8.5  11.7  11.5   8.1
21        Хмельницька  23.4  19.8  14.8  12.9   8.5  11.3  11.2   7.9
22          Черкаська  20.5  17.9  14.4  12.3   7.5  10.0   9.8   6.4
23        Чернівецька  24.7  21.8  17.0  14.8  10.1  12.8  12.9   9.2
24       Чернігівська  22.0  18.3  12.7  10.8   6.9   9.4   9.0   6.1
25               Київ   NaN  17.4  15.9  12.0   7.3  12.0  12.1  11.0
26        Севастополь   NaN   NaN   NaN  12.5   7.0  12.0     —     —

In [ ]:
df["Регіон"][1]

'Вінницька'